/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EmpresaCompanyRouteImport } from './routes/empresa.$company'
import { Route as EmpresaCompanyConductorDriverRouteImport } from './routes/empresa.$company.conductor.$driver'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EmpresaCompanyRoute = EmpresaCompanyRouteImport.update({
  id: '/empresa/$company',
  path: '/empresa/$company',
  getParentRoute: () => rootRouteImport,
} as any)
const EmpresaCompanyConductorDriverRoute =
  EmpresaCompanyConductorDriverRouteImport.update({
    id: '/conductor/$driver',
    path: '/conductor/$driver',
    getParentRoute: () => EmpresaCompanyRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/empresa/$company': typeof EmpresaCompanyRouteWithChildren
  '/empresa/$company/conductor/$driver': typeof EmpresaCompanyConductorDriverRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/empresa/$company': typeof EmpresaCompanyRouteWithChildren
  '/empresa/$company/conductor/$driver': typeof EmpresaCompanyConductorDriverRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/empresa/$company': typeof EmpresaCompanyRouteWithChildren
  '/empresa/$company/conductor/$driver': typeof EmpresaCompanyConductorDriverRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/empresa/$company' | '/empresa/$company/conductor/$driver'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/empresa/$company' | '/empresa/$company/conductor/$driver'
  id:
    | '__root__'
    | '/'
    | '/empresa/$company'
    | '/empresa/$company/conductor/$driver'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  EmpresaCompanyRoute: typeof EmpresaCompanyRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/empresa/$company': {
      id: '/empresa/$company'
      path: '/empresa/$company'
      fullPath: '/empresa/$company'
      preLoaderRoute: typeof EmpresaCompanyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/empresa/$company/conductor/$driver': {
      id: '/empresa/$company/conductor/$driver'
      path: '/conductor/$driver'
      fullPath: '/empresa/$company/conductor/$driver'
      preLoaderRoute: typeof EmpresaCompanyConductorDriverRouteImport
      parentRoute: typeof EmpresaCompanyRoute
    }
  }
}

interface EmpresaCompanyRouteChildren {
  EmpresaCompanyConductorDriverRoute: typeof EmpresaCompanyConductorDriverRoute
}

const EmpresaCompanyRouteChildren: EmpresaCompanyRouteChildren = {
  EmpresaCompanyConductorDriverRoute: EmpresaCompanyConductorDriverRoute,
}

const EmpresaCompanyRouteWithChildren = EmpresaCompanyRoute._addFileChildren(
  EmpresaCompanyRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  EmpresaCompanyRoute: EmpresaCompanyRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
